# This file has been moved to /config/docker/docker-compose.override.yml
# To use the override file, run:
# docker-compose -f docker-compose.yml -f config/docker/docker-compose.override.yml up

# Or create a symlink:
# ln -s config/docker/docker-compose.override.yml docker-compose.override.yml