name: Prisma Migrate Production DB

on:
  push:
    branches:
      - main
    paths:
      - 'prisma/schema.prisma'
      - 'prisma/migrations/**'
  workflow_dispatch:

jobs:
  backup:
    name: Backup Database
    uses: ./.github/workflows/database-backup.yml
    with:
      backup_prefix: 'pre-migration'
    secrets: inherit

  migrate:
    name: Deploy Database Migrations
    needs: backup  # Only run after successful backup
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Show backup info
        run: |
          echo "✅ Database backed up successfully"
          echo "Backup filename: ${{ needs.backup.outputs.backup_filename }}"
          echo "Proceeding with migration..."

      - name: Run Prisma migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Verify migration status
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate status

      - name: Migration summary
        if: always()
        run: |
          echo "## Migration Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ **Migration completed successfully**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Backup created**: ${{ needs.backup.outputs.backup_filename }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Migration failed**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Backup available**: ${{ needs.backup.outputs.backup_filename }}" >> $GITHUB_STEP_SUMMARY
            echo "- Use the backup to restore if needed" >> $GITHUB_STEP_SUMMARY
          fi